# DATABASE SAHAM HARDCODED (ANTI GAGAL)
# Berisi 600+ Emiten Aktif Bursa Efek Indonesia

# Daftar ini kita tulis manual sebagai String panjang agar tidak perlu download
# dan tidak kena blokir server manapun.

DATA_MENTAH = """
BBCA BBRI BMRI BBNI TLKM ASII UNTR ICBP INDF GOTO KLBF ADRO AMRT MDKA PGAS
PTBA ITMG UNVR SMGR INKP CPIN BRIS ARTO BBTN ANTM TINS INCO MEDC AKRA EXCL
ISAT MTEL PGEO MBMA NCKL AMMN HRUM ESSA ELSA BUMI BRMS DOID ENRG INDY ADMR
KKGI TOBA ABMM CTRA BSDE PWON SMRA ASRI APLN PANI DMAS WIKA PTPP ADHI WSKT
WEGE TOTL JRPT KIJA MYOR JPFA MAIN GGRM HMSP WIIM SIDO ACES MAPI MAPA ERAA
RALS LPPF MIDI ROTI ULTJ CMRY CLEO STTP BSBK DEWA PSAB AWAN FREN GZCO ZINC
KAEF IRRA KRYA GULA JARR WIRG AXIO TRGU DESE OLIV SAGE NICE ASLI STRK MUTU
AEGS GTRA HATM INET IRSX MAXI MSKY WIDI BREN CUAN TPIA VKTR RAME LMAX MPXL
SMGA LIVE BAI CGAS SEMA UANG WAPO PACK IOTF GOLF HYGN RGAS MANG PTPS VTNY
AREA BABY SURI TOSK BLES BPII BULL PSSI SMDR TMAS TNCA TPMA TRUK WINS IPCC
IPCM JAWA JSMR KEEN KBLI KBLM KDSI KETR KKGI KOPI KPIG KRAS KREN LAND LEAD
LINK LMAS LMSH LPCK LPKR LPLI LPPS LSIP LTLS LUCK LUCY MABA MAGP MAMI MAPB
MARI MARK MASA MAYA MBAP MBSS MBTO MCAS MCHA MCOL MDLN MDRN MEJA MENT MERK
META MFIN MFMI MGNA MGRO MICE MIKA MINA MIRA MITI MKNT MKPI MLBI MLIA MLPL
MLPT MMLP MNCN MOLI MORA MPMX MPOW MPPA MPRO MRAT MREI MSIN MTMH MTLA MTLJ
MTPS MTRA MTRY MTSM MYOH MYRX MYTX NALA NASA NASI NATO NELY NETV NFCX NIKL
NIPS NIRO NISP NOBU NPGF NRCA NUSA NZIA OASA OBMD OCAP OKAS OMRE OMET PADI
PALM PAMG PANR PANS PBID PBRX PBSA PCAR PDES PEGE PEHA PGLI PGS PGJO PICO
PJAA PKPK PLIN PLAS PMJS PNBN PNBS PNLF PNSE POLA POLI POLL POLY POOL PORT
POSA POWR PPRE PPRO PRAS PRDA PRIM PSGO PSKT PTDU PTIS PTPW PTSN PTSP PUDP
PURA PUSA PYFA PZZA RAJA RANC RBMS RDTX REAL RELI RISE RMBA ROCK RODA RUIS
RWE SAFE SAME SAMF SAPX SATU SCCO SCMA SCNP SCPI SDMU SDPC SDRA SGER SGRO
SHID SHIP SILO SIMA SIMP SINI SIPD SKBM SKLT SKRN SKYB SLIS SMAR SMBR SMCB
SMDM SMKL SMMA SMRU SMSM SNLK SOCI SOFA SOHO SONA SPMA SPTN SQMI SRAJ SRIL
SRSN SRTG SSIA SSMS SSTM STAR SUDI SUGI SULI SUPR SURE SWAT TARA TAXI TBIG
TBLA TBMS TCID TCPI TDPM TEBE TECH TELE TFCO TGKA TGRA TIFA TIRA TIRT TKIM
TMPO TOPS TOTO TOWR TPNI TRAM TRIL TRIM TRIN TRIO TRIS TRJA TRST TSPC TUGU
TURI UNIC UNIQ UNIT UNSP URBN VICI VINS VIVA VOKS VRNA WEHA WICO WOMF WOOD
WOWS WTON YELO YPAS YES YULE ZBRA ZONA ZYRX 
"""

def get_semua_saham():
    # Teknik memecah teks menjadi list
    # .replace -> bersihkan baris baru
    # .split -> potong berdasarkan spasi
    print("📂 Memuat Database Internal (600+ Emiten)...")
    
    list_saham = []
    # Bersihkan spasi dan enter
    raw_list = DATA_MENTAH.replace("\n", " ").split(" ")
    
    for s in raw_list:
        kode = s.strip()
        if len(kode) == 4: # Pastikan kodenya 4 huruf
            list_saham.append(kode + ".JK")
            
    # Hapus duplikat dan urutkan abjad
    final_list = sorted(list(set(list_saham)))
    
    print(f"✅ SUKSES! {len(final_list)} Saham siap dipantau.")
    return final_list

# Variabel yang dipanggil oleh api_saham.py
semua_saham = get_semua_saham()